name: Test

on:
  push:
    branches:
      - master
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      RUST_LOG: bitcoind=debug
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        feature:
          [
            "25_1",
            "25_0",
            "24_0_1",
            "23_1",
            "22_1",
            "0_21_2",
            "0_20_2",
            "0_19_1",
            "0_18_1",
            "0_17_1",
          ]
        include:
          - os: "macos-11"
            feature: "25_1"
          - os: "windows-2019"
            feature: "25_1"

    steps:
      - run: df -h
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.feature }}${{ matrix.os }}
        if: ${{ matrix.os != 'macos-11' }}  # issue with hard-links on mac
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --features ${{ matrix.feature }}
      - run: echo "BITCOIND_EXE=$(find ./target/debug -name bitcoind)" >> $GITHUB_ENV
        if: ${{ matrix.os != 'windows-2019' }}
      - run: cargo test
        if: ${{ matrix.feature != '0_18_1' &&  matrix.feature != '0_17_1' && matrix.os != 'windows-2019' }}  # would fail `test_multi_wallet`


  cosmetics:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings

  rust-version:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        toolchain: ["1.48.0", "stable", "nightly"]

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.version }}1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: |
          cargo update
          cargo update -p which --precise 4.2.5
          cargo update -p tempfile --precise 3.3.0
          cargo update -p log --precise 0.4.18
          cargo update -p serde_json --precise 1.0.99
          cargo update -p serde --precise 1.0.156
          cargo update -p regex --precise 1.7.3
          cargo update -p quote --precise 1.0.28
          cargo update -p proc-macro2 --precise 1.0.63
        if: ${{ matrix.toolchain == '1.48.0' }}
      - run: cargo build

  build-nix:
    runs-on: ubuntu-20.04
    env:
      FNAME: bitcoin-23.1-x86_64-linux-gnu.tar.gz
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: echo "BITCOIND_TARBALL_FILE=./${FNAME}" >> $GITHUB_ENV
      - run: cargo build --features 23_1 && exit 1 || exit 0
      - run: wget -q https://bitcoincore.org/bin/bitcoin-core-23.1/${FNAME}
      - run: cargo build --features 23_1
